name: Build and Publish to AWS CodeArtifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2.2.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com
        
    - name: Get CodeArtifact authorization token
      id: get-token
      run: |
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
          --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} \
          --query authorizationToken \
          --output text)
        echo "CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> $GITHUB_ENV
        
        CODEARTIFACT_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint \
          --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
          --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} \
          --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} \
          --format maven \
          --query repositoryEndpoint \
          --output text)
        echo "CODEARTIFACT_REPOSITORY_URL=${CODEARTIFACT_REPOSITORY_URL}" >> $GITHUB_ENV
        
    - name: Generate version
      run: |
        # Generate version based on timestamp and commit hash
        VERSION="1.0.0-$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build and Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        ./gradlew build publishArtifacts
      env:
        CODEARTIFACT_AUTH_TOKEN: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
        CODEARTIFACT_REPOSITORY_URL: ${{ env.CODEARTIFACT_REPOSITORY_URL }}
        VERSION: ${{ env.VERSION }} 